$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$
$$\newcommand{\braket}[2]{\left\langle{#1}\middle|{#2}\right\rangle}$$
$$\newcommand{\E}[1]{\left\langle{#1}\right\rangle}$$

- Recap

$$f(\hat{H})=f(\lambda)\ket{\psi}$$
$$\braket{x'}{x}=\delta(x-x')$$
$$I' = \int_{\rm I\!R}^{}dx'\ket{x'}\bra{x}$$
$$\braket{\phi}{\psi} = \int_{R}dx\braket{\phi}{x}{x}{\psi} = \int_{R}dx\phi^{\ast}(x)\psi(x)$$
$$\E{\hat{x}}_\psi = \bra{\psi}\hat{x}\ket{\psi} = \int dx\,x|\psi(x)|^2$$
$$\E{f(\hat{x})_\psi} = \int dx\,f(x)|\psi(x)|^2$$

  It can be rewrite as:

$$\bra{\psi}f(\hat{x}\ket{\psi} = \int dx\,\bra{\psi}f(\hat{x})\ket{x}\braket{x}{\psi}=\int dx \bra{\psi}f(x)\ket{x}\braket{x}{\psi} = \int dx\, f(x)\braket{\psi}{x}\braket{x}{\psi} = \int dx\, f(x)\psi^{\ast}\psi(x)$$

- Translation operator $$\hat{T}(a)$$

$$\hat{T}\hat{T}^\dagger = \hat{T}^\dagger \hat{T} = \hat{I}$$

- Errata: T is unitary, not hermite

- as a tends to be 0
$$\frac{d}{da}\hat{T}(a)\bracevert_{a=0}=iG\, ,\, \hat{G}^\dagger = \hat{G}$$

$$[a\hat{G}]=1\, ,[a]=[L]\rightarrow [\hat{G}]=[\frac{1}{L}] \leadsto \frac{\hat{P}}{\hbar}$$

In [37]:
#eigen decomposition
from numpy import linalg as LA
from numpy import multiply
from numpy import dot
import numpy as np
a = np.array([[1, 1j], [-1j, 1]])
w, v = LA.eig(a)

#verify

#horizontal combine two eigenvalues


In [38]:
D = np.diag(w)

In [56]:
M=np.hstack((v[1],v[0])).reshape((2,2))

In [57]:
dot(dot(M.T,D),M)#still !=a

array([[ 1.+0.j,  0.+1.j],
       [ 0.+1.j, -1.+0.j]])

In [60]:
a

array([[ 1.+0.j,  0.+1.j],
       [-0.-1.j,  1.+0.j]])

In [54]:
w

array([2.+0.j, 0.+0.j])

In [61]:
string = 'abc'

In [62]:
string.startswith('a')

True

In [63]:
import nltk